version: "3"

services:
  frontend:
    image: shauryachandhoke/black-scholes-merton-calculator-frontend:v1
    working_dir: /code
    ports:
      - "4200:4200"
    depends_on:
      - backend
    volumes:
      - ${PWD}/client/:/code
      - /code/node_modules

  backend:
    image: shauryachandhoke/black-scholes-merton-calculator-backend:v1
    working_dir: /code
    ports:
      - "8080:8080"
